Running test 165: pureJava/nameConflicts/type and package name conflicts caught as errors (1)
Commandline: abc -d pureJava/nameConflicts pureJava/nameConflicts/p1/p2.java pureJava/nameConflicts/p1/Main1.java pureJava/nameConflicts/p1/Foo.java pureJava/nameConflicts/p1/p2/Foo.java 
Compilation succeeded but was expected to fail.
FAIL: Test 165: "pureJava/nameConflicts/type and package name conflicts caught as errors (1)" failed.


Running test 178: pureJava/nested finally blocks have interesting frame location problems
Commandline: abc -d pureJava pureJava/NestedFinally.java 
Compilation produced an unexpected number of errors: 1, should be 0
Actual errors found: 
Semantic Error at pureJava/NestedFinally.java:5,18-35: Missing return statement.
FAIL: Test 178: "pureJava/nested finally blocks have interesting frame location problems" failed.


Running test 418: new/join points exist in the execution of field initializers
Commandline: abc -d new new/FieldInitializerJoinPoints.java 
Test failed, compiled class behaved incorrectly
Message: fail ncount: 0 < 1
org.aspectj.bridge.AbortException: ncount: 0 < 1
	at org.aspectj.bridge.MessageWriter.handleMessage(MessageWriter.java:47)
	at org.aspectj.testing.Tester.handle(Tester.java:963)
	at org.aspectj.testing.Tester.checkFailed(Tester.java:177)
	at org.aspectj.testing.Tester.checkEqual(Tester.java:462)
	at FieldInitializerJoinPoints.main(FieldInitializerJoinPoints.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at abc.testing.TestCase.runTest(TestCase.java:393)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
FAIL: Test 418: "new/join points exist in the execution of field initializers" failed.


Running test 472: new/primitive parameters coercable to Object just like return values are
Commandline: abc -d new new/ObjectForInt.java 
Test failed, compiled class behaved incorrectly
Message: fail Test.a: 4 < 10
org.aspectj.bridge.AbortException: Test.a: 4 < 10
	at org.aspectj.bridge.MessageWriter.handleMessage(MessageWriter.java:47)
	at org.aspectj.testing.Tester.handle(Tester.java:963)
	at org.aspectj.testing.Tester.checkFailed(Tester.java:177)
	at org.aspectj.testing.Tester.checkEqual(Tester.java:462)
	at ObjectForInt.main(ObjectForInt.java:6)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at abc.testing.TestCase.runTest(TestCase.java:393)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
FAIL: Test 472: "new/primitive parameters coercable to Object just like return values are" failed.


Running test 496: new/elaborated into testing of around on all join points
Commandline: abc -d new new/AroundAll.java 
Test failed, compiled class behaved incorrectly
Message: fail steps expected array of length 114 got 126
org.aspectj.bridge.AbortException: steps expected array of length 114 got 126
	at org.aspectj.bridge.MessageWriter.handleMessage(MessageWriter.java:47)
	at org.aspectj.testing.Tester.handle(Tester.java:963)
	at org.aspectj.testing.Tester.checkFailed(Tester.java:177)
	at org.aspectj.testing.Tester.checkEqual(Tester.java:228)
	at A.checkLog(AroundAll.java:176)
	at AroundAll.abc$static$proceed$A$around$1601(AroundAll.java:9)
	at A.around$1601(AroundAll.java:199)
	at AroundAll.main(AroundAll.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at abc.testing.TestCase.runTest(TestCase.java:393)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
FAIL: Test 496: "new/elaborated into testing of around on all join points" failed.


Running test 555: new/accessing protected superclass members in and outside CCC from body of method introduction
Commandline: abc -d new new/SuperInIntroduction.java 
InvocationTargetException while trying to run compiled class: java.lang.VerifyError: (class: A, method: getClone signature: (LObjectSub;)LObjectSub;) Bad access to protected data
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at abc.testing.TestCase.runTest(TestCase.java:393)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
Caused by: java.lang.VerifyError: (class: A, method: getClone signature: (LObjectSub;)LObjectSub;) Bad access to protected data
	at Sub.getInt(SuperInIntroduction.java)
	at SuperInIntroduction.main(SuperInIntroduction.java:6)
	... 7 more
FAIL: Test 555: "new/accessing protected superclass members in and outside CCC from body of method introduction" failed.


Running test 64301: abctests/new/type pattern matching for inner classes (from Ken Horn)
Commandline: abc -d abctests/new abctests/new/test/TypePat.java 
Test failed, compiled class behaved incorrectly
Message: fail [ expected event "A.before2: C.foo()" not found]
org.aspectj.bridge.AbortException: [ expected event "A.before2: C.foo()" not found]
	at org.aspectj.bridge.MessageWriter.handleMessage(MessageWriter.java:47)
	at org.aspectj.testing.Tester.handle(Tester.java:963)
	at org.aspectj.testing.Tester.checkFailed(Tester.java:177)
	at org.aspectj.testing.Tester.check(Tester.java:204)
	at org.aspectj.testing.Tester.checkEqualIgnoreDups(Tester.java:702)
	at org.aspectj.testing.Tester.checkEqual(Tester.java:742)
	at org.aspectj.testing.Tester.checkEvents(Tester.java:922)
	at org.aspectj.testing.Tester.checkAndClearEvents(Tester.java:933)
	at test.TypePat.main(TypePat.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at abc.testing.TestCase.runTest(TestCase.java:393)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
FAIL: Test 64301: "abctests/new/type pattern matching for inner classes (from Ken Horn)" failed.


Running test 667: pureJava/assert coverage tests in one package [requires 1.4]
Commandline: abc -d pureJava -source 1.4 pureJava/AssertInOnePackage.java 
Unexpected exception while compiling: polyglot.util.InternalCompilerError: unhandled exception during compilation
polyglot.util.InternalCompilerError: unhandled exception during compilation
	at abc.main.Main.run(Main.java:581)
	at abc.testing.TestCase.runTest(TestCase.java:287)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
Caused by: java.util.NoSuchElementException: No such class: InnerStaticInitializerOnHelperI$11
	at abc.weaving.aspectinfo.AbcFactory.sootClassToClassType(AbcFactory.java:93)
	at abc.aspectj.visit.PCStructure.insertClassAndSuperclasses(PCStructure.java:163)
	at abc.aspectj.visit.PCStructure.updateWithAllSootClasses(PCStructure.java:178)
	at abc.aspectj.visit.PatternMatcher.updateWithAllSootClasses(PatternMatcher.java:125)
	at abc.main.Main.weave(Main.java:789)
	at abc.main.Main.run(Main.java:523)
	... 3 more
FAIL: Test 667: "pureJava/assert coverage tests in one package [requires 1.4]" failed.


Running test 752: bugs/problems with finalize call
Commandline: abc -d bugs bugs/Finalizer.java 
Compilation succeeded but was expected to fail.
FAIL: Test 752: "bugs/problems with finalize call" failed.


Running test 77201: abctests/bugs/declare soft and throw statements
Commandline: abc -d abctests/bugs abctests/bugs/ConvertToUnchecked.java 
Compilation produced an unexpected number of errors: 1, should be 0
Actual errors found: 
Semantic Error at ConvertToUnchecked.java:44,2-11: The exception java.io.IOException must be either caught or declared to be thrown
FAIL: Test 77201: "abctests/bugs/declare soft and throw statements" failed.


Running test 979: abctests/bugs/pack1/packages in wrong place
Commandline: abc -d abctests/bugs/pack1 abctests/bugs/pack1/A/B.java 
Unexpected exception while compiling: polyglot.util.InternalCompilerError: exception while resolving C.B
polyglot.util.InternalCompilerError: exception while resolving C.B
	at abc.aspectj.visit.Jimplify$AbcClassSource.resolve(Jimplify.java:88)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:147)
	at soot.SootResolver.bringToSignatures(SootResolver.java:168)
	at soot.SootResolver.bringToBodies(SootResolver.java:210)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:102)
	at soot.SootResolver.resolveClass(SootResolver.java:88)
	at soot.Scene.loadClass(Scene.java:329)
	at abc.main.Main.compile(Main.java:738)
	at abc.main.Main.run(Main.java:519)
	at abc.testing.TestCase.runTest(TestCase.java:287)
	at abc.testing.Main.doCase(Main.java:282)
	at abc.testing.Main.main(Main.java:116)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1438)
	at java.lang.String.substring(String.java:1411)
	at soot.javaToJimple.InitialResolver.createClassToSourceMap(InitialResolver.java:173)
	at soot.javaToJimple.InitialResolver.resolveAST(InitialResolver.java:144)
	at abc.aspectj.visit.Jimplify$AbcClassSource.resolve(Jimplify.java:81)
	... 11 more
FAIL: Test 979: "abctests/bugs/pack1/packages in wrong place" failed.


Running test 981: abctests/bugs/problem with byte constants
Commandline: abc -d abctests/bugs abctests/bugs/ByteProblem.java 
Compilation produced an unexpected number of errors: 1, should be 0
Actual errors found: 
Semantic Error at abctests/bugs/ByteProblem.java:8,8-24: No valid method call found for foo(int) in ByteProblem.
FAIL: Test 981: "abctests/bugs/problem with byte constants" failed.


